sudo: required

language: go

go:
  - "1.10"

services:
  - docker

env:
  global:
    - IMAGE_NAME=ci/testing
    - DOCKERFILE=docker/Dockerfile.testing

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - docker build -f "$DOCKERFILE" -t "$IMAGE_NAME" .
  - docker run -it --rm "$IMAGE_NAME"
