# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.


[[projects]]
  name = "github.com/inconshreveable/mousetrap"
  packages = ["."]
  revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
  version = "v1.0"

[[projects]]
  name = "github.com/spf13/cobra"
  packages = ["."]
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b"
  version = "v0.0.1"

[[projects]]
  name = "github.com/spf13/pflag"
  packages = ["."]
  revision = "e57e3eeb33f795204c1ca35f56c44f83227c6e66"
  version = "v1.0.0"

[[projects]]
  branch = "master"
  name = "golang.org/x/sys"
  packages = ["unix"]
  revision = "37707fdb30a5b38865cfb95e5aab41707daec7fd"

[solve-meta]
  analyzer-name = "dep"
  analyzer-version = 1
  inputs-digest = "fd1a93ea6ef0a4f0665bed43b7c7a303774ea3e1e772f3178f284a840e2f6c04"
  solver-name = "gps-cdcl"
  solver-version = 1
