version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f ./docker/Dockerfile.testing -v `pwd`/.git:/go/src/github.com/dominicbreuker/pspy/.git  -t local/pspy-testing:latest . 
      - run: docker run -it local/pspy-testing:latest
